import streamlit as st
import requests
import pandas as pd


# --------------------------------------------------
# Configuration
# --------------------------------------------------

API_URL = "http://127.0.0.1:5000"


# --------------------------------------------------
# Page Configuration
# --------------------------------------------------

st.set_page_config(
    page_title="Car Price Prediction",
    page_icon="🚗",
    layout="wide"
)


# --------------------------------------------------
# Title
# --------------------------------------------------

st.title("🚗 Car Price Prediction")

st.write(
    "Predict the selling price of a used car using a "
    "machine learning model."
)

st.divider()


# --------------------------------------------------
# Sidebar
# --------------------------------------------------

st.sidebar.header("About the Project")

st.sidebar.write(
    """
    This application uses a machine learning regression
    model to estimate the selling price of used cars.

    The prediction is generated through a Flask API
    and stored in a SQLite database.
    """
)

st.sidebar.info(
    "Oasis Infobyte Data Science Internship - Task 3"
)


# --------------------------------------------------
# Car Details Form
# --------------------------------------------------

st.subheader("Enter Car Details")

col1, col2 = st.columns(2)


with col1:

    brand = st.text_input(
        "Car Brand / Model",
        placeholder="Example: Maruti"
    )

    present_price = st.number_input(
        "Present Price",
        min_value=0.0,
        value=5.0,
        step=0.1
    )

    kms_driven = st.number_input(
        "Kilometers Driven",
        min_value=0.0,
        value=25000.0,
        step=1000.0
    )

    car_age = st.number_input(
        "Car Age (Years)",
        min_value=0,
        max_value=50,
        value=5,
        step=1
    )


with col2:

    fuel_type = st.selectbox(
        "Fuel Type",
        [
            "Petrol",
            "Diesel",
            "CNG"
        ]
    )

    seller_type = st.selectbox(
        "Seller Type",
        [
            "Dealer",
            "Individual"
        ]
    )

    transmission = st.selectbox(
        "Transmission",
        [
            "Manual",
            "Automatic"
        ]
    )

    owner = st.number_input(
        "Previous Owners",
        min_value=0,
        max_value=5,
        value=0,
        step=1
    )


st.divider()


# --------------------------------------------------
# Prediction Button
# --------------------------------------------------

if st.button(
    "🔮 Predict Car Price",
    type="primary",
    use_container_width=True
):

    # Input validation

    if not brand.strip():

        st.error(
            "Please enter the car brand/model."
        )

    else:

        # Prepare API data

        payload = {
            "Present_Price": present_price,
            "Kms_Driven": kms_driven,
            "Fuel_Type": fuel_type,
            "Seller_Type": seller_type,
            "Transmission": transmission,
            "Owner": owner,
            "Car_Age": car_age,
            "Brand": brand.strip()
        }

        try:

            # Send request to Flask

            response = requests.post(
                f"{API_URL}/predict",
                json=payload,
                timeout=10
            )

            # Successful request

            if response.status_code == 200:

                result = response.json()

                predicted_price = result[
                    "predicted_price"
                ]

                st.success(
                    "Prediction completed successfully!"
                )

                st.metric(
                    label="Estimated Selling Price",
                    value=f"₹ {predicted_price:.2f} Lakhs"
                )

                st.info(
                    "The predicted price is generated by "
                    "the trained machine learning model."
                )

            else:

                error_data = response.json()

                st.error(
                    error_data.get(
                        "error",
                        "Prediction failed."
                    )
                )

        except requests.exceptions.ConnectionError:

            st.error(
                "Unable to connect to the Flask API. "
                "Please make sure the backend is running."
            )

        except requests.exceptions.Timeout:

            st.error(
                "The request timed out. "
                "Please try again."
            )

        except Exception as e:

            st.error(
                f"Unexpected error: {e}"
            )


# --------------------------------------------------
# Prediction History
# --------------------------------------------------

st.divider()

st.subheader("📋 Prediction History")


if st.button(
    "🔄 Refresh History",
    use_container_width=True
):

    try:

        response = requests.get(
            f"{API_URL}/history",
            timeout=10
        )

        if response.status_code == 200:

            result = response.json()

            predictions = result.get(
                "predictions",
                []
            )

            if predictions:

                history_df = pd.DataFrame(
                    predictions
                )

                # Rename columns for UI

                history_df = history_df.rename(
                    columns={
                        "id": "ID",
                        "present_price": "Present Price",
                        "kms_driven": "Kms Driven",
                        "fuel_type": "Fuel Type",
                        "seller_type": "Seller Type",
                        "transmission": "Transmission",
                        "owner": "Previous Owners",
                        "car_age": "Car Age",
                        "brand": "Brand",
                        "predicted_price": "Predicted Price",
                        "created_at": "Created At"
                    }
                )

                st.dataframe(
                    history_df,
                    use_container_width=True,
                    hide_index=True
                )

            else:

                st.info(
                    "No prediction history available."
                )

        else:

            st.error(
                "Unable to retrieve prediction history."
            )

    except requests.exceptions.ConnectionError:

        st.error(
            "Unable to connect to the Flask API. "
            "Please make sure the backend is running."
        )

    except Exception as e:

        st.error(
            f"Unexpected error: {e}"
        )


# --------------------------------------------------
# Footer
# --------------------------------------------------

st.divider()

st.caption(
    "Car Price Prediction | "
    "Oasis Infobyte Data Science Internship"
)